name: Build and Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    name: Build and deploy archive
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      
      - name: Build archive
        run: npm run build

      - name: GitHub Pages - Deploy articles
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: archive

      - name: GitHub Pages - Deploy assets
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: assets
          branch: resources

      - name: Dispatch notification to web application repository
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
          script: |
            const res = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'DevBlog-Website',
              workflow_id: 'firebase-hosting-merge.yml',
              ref: 'main'
            });
            console.log(res);
