name: Node.js lint archive files

on:
  workflow_dispatch:
  merge:
  pull_request:

jobs:
  runs-on: "ubuntu-latest"
  timeout-minutes: 5

  steps:

    - name: Setup node
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048
      with:
        node-version: '16.15.0'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Lint files
      run: npm run lint
