name: Node.js lint archive files

on:
  pull_request:
  merge:

permissions:
  contents: read

jobs:
  runs-on: "ubuntu-latest"
  timeout-minutes: 5

  steps:

    - name: Install dependencies
      run: npm ci

    - name: Lint files
      run: npm run lint